#include <ntddk.h>
#include <wdf.h>
#include <initguid.h>
#include <guiddef.h>
#include "resource_contract.h"

#define PHASER_M051_MAGIC 0x354D4850u
#define PHASER_M051_VERSION 0x00050100u


#define HDA_REG_GCAP   0x0000u
#define HDA_REG_VMIN   0x0002u
#define HDA_REG_VMAJ   0x0003u

#define DSP_REG_ADSPCS 0x0004u
#define DSP_REG_ADSPIS 0x000Cu

#define IOCTL_PHASER_M051_SNAPSHOT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_READ_ACCESS)

// {6E816B38-0149-4DC7-A3B3-79DF42DD6511}
DEFINE_GUID(GUID_DEVINTERFACE_PHASER_M051_RO,
    0x6e816b38, 0x0149, 0x4dc7, 0xa3, 0xb3, 0x79, 0xdf, 0x42, 0xdd, 0x65, 0x11);

typedef struct _PHASER_M051_SNAPSHOT {
    ULONG Magic;
    ULONG Version;
    ULONGLONG HdaPhysical;
    ULONGLONG DspPhysical;
    ULONG HdaLength;
    ULONG DspLength;
    ULONG HdaGcap;
    ULONG HdaVersion;
    ULONG DspAdspcs;
    ULONG DspAdspis;
    ULONG Flags;
    ULONG Reserved;
} PHASER_M051_SNAPSHOT, *PPHASER_M051_SNAPSHOT;

static_assert(sizeof(PHASER_M051_SNAPSHOT) == 56,
    "Unexpected PHASER_M051_SNAPSHOT size.");

typedef struct _PHASER_M051_CONTEXT {
    PHYSICAL_ADDRESS HdaPhysical;
    PHYSICAL_ADDRESS DspPhysical;
    ULONG HdaLength;
    ULONG DspLength;
    PUCHAR HdaBase;
    PUCHAR DspBase;
    BOOLEAN ResourcesReady;
} PHASER_M051_CONTEXT, *PPHASER_M051_CONTEXT;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(PHASER_M051_CONTEXT, PhaserM051GetContext)

extern "C" DRIVER_INITIALIZE DriverEntry;
EVT_WDF_DRIVER_DEVICE_ADD PhaserM051EvtDeviceAdd;
EVT_WDF_DEVICE_PREPARE_HARDWARE PhaserM051EvtPrepareHardware;
EVT_WDF_DEVICE_RELEASE_HARDWARE PhaserM051EvtReleaseHardware;
EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL PhaserM051EvtIoDeviceControl;

extern "C"
NTSTATUS
DriverEntry(
    _In_ PDRIVER_OBJECT DriverObject,
    _In_ PUNICODE_STRING RegistryPath
)
{
    WDF_DRIVER_CONFIG config;
    WDF_DRIVER_CONFIG_INIT(&config, PhaserM051EvtDeviceAdd);

    return WdfDriverCreate(
        DriverObject,
        RegistryPath,
        WDF_NO_OBJECT_ATTRIBUTES,
        &config,
        WDF_NO_HANDLE);
}

NTSTATUS
PhaserM051EvtDeviceAdd(
    _In_ WDFDRIVER Driver,
    _Inout_ PWDFDEVICE_INIT DeviceInit
)
{
    UNREFERENCED_PARAMETER(Driver);

    WdfDeviceInitSetExclusive(DeviceInit, TRUE);
    WdfDeviceInitSetCharacteristics(DeviceInit,
        FILE_DEVICE_SECURE_OPEN | FILE_AUTOGENERATED_DEVICE_NAME, TRUE);
    // Restrict the diagnostic interface to SYSTEM and elevated administrators.
    DECLARE_CONST_UNICODE_STRING(sddl, L"D:P(A;;GA;;;SY)(A;;GA;;;BA)");
    NTSTATUS securityStatus = WdfDeviceInitAssignSDDLString(DeviceInit, &sddl);
    if (!NT_SUCCESS(securityStatus)) { return securityStatus; }
    WdfDeviceInitSetIoType(DeviceInit, WdfDeviceIoBuffered);

    WDF_PNPPOWER_EVENT_CALLBACKS pnp;
    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnp);
    pnp.EvtDevicePrepareHardware = PhaserM051EvtPrepareHardware;
    pnp.EvtDeviceReleaseHardware = PhaserM051EvtReleaseHardware;
    WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &pnp);

    WDF_OBJECT_ATTRIBUTES attributes;
    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&attributes, PHASER_M051_CONTEXT);

    WDFDEVICE device = nullptr;
    NTSTATUS status = WdfDeviceCreate(&DeviceInit, &attributes, &device);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    auto ctx = PhaserM051GetContext(device);
    RtlZeroMemory(ctx, sizeof(*ctx));

    status = WdfDeviceCreateDeviceInterface(
        device,
        &GUID_DEVINTERFACE_PHASER_M051_RO,
        nullptr);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    WDF_IO_QUEUE_CONFIG queue;
    WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&queue, WdfIoQueueDispatchSequential);
    queue.EvtIoDeviceControl = PhaserM051EvtIoDeviceControl;
    queue.PowerManaged = WdfTrue;

    return WdfIoQueueCreate(
        device,
        &queue,
        WDF_NO_OBJECT_ATTRIBUTES,
        WDF_NO_HANDLE);
}

NTSTATUS
PhaserM051EvtPrepareHardware(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesRaw,
    _In_ WDFCMRESLIST ResourcesTranslated
)
{
    UNREFERENCED_PARAMETER(ResourcesRaw);

    auto ctx = PhaserM051GetContext(Device);
    ctx->ResourcesReady = FALSE;
    ctx->HdaBase = nullptr;
    ctx->DspBase = nullptr;
    ctx->HdaLength = 0;
    ctx->DspLength = 0;
    ctx->HdaPhysical.QuadPart = 0;
    ctx->DspPhysical.QuadPart = 0;

    PCM_PARTIAL_RESOURCE_DESCRIPTOR memory[2] = {};
    ULONG memoryCount = 0;

    const ULONG count = WdfCmResourceListGetCount(ResourcesTranslated);
    for (ULONG i = 0; i < count; ++i) {
        auto desc = WdfCmResourceListGetDescriptor(ResourcesTranslated, i);
        if (desc == nullptr) {
            return STATUS_DEVICE_CONFIGURATION_ERROR;
        }

        if (desc->Type == CmResourceTypeMemory) {
            if (memoryCount >= RTL_NUMBER_OF(memory)) {
                return STATUS_DEVICE_CONFIGURATION_ERROR;
            }
            memory[memoryCount++] = desc;
        }
    }

    if (memoryCount != 2) {
        return STATUS_DEVICE_CONFIGURATION_ERROR;
    }

    // Microsoft documents PCI resources in BAR order, with other resource types
    // possibly interleaved. Filtering only CmResourceTypeMemory therefore keeps
    // the two live memory BARs in order: BAR0/HDA, then BAR4/DSP.
    const ULONGLONG hdaPhys = static_cast<ULONGLONG>(memory[0]->u.Memory.Start.QuadPart);
    const ULONGLONG dspPhys = static_cast<ULONGLONG>(memory[1]->u.Memory.Start.QuadPart);

    if (!phaser360::valid_resources(hdaPhys, memory[0]->u.Memory.Length,
            dspPhys, memory[1]->u.Memory.Length)) {
        return STATUS_DEVICE_CONFIGURATION_ERROR;
    }

    ctx->HdaPhysical = memory[0]->u.Memory.Start;
    ctx->DspPhysical = memory[1]->u.Memory.Start;
    ctx->HdaLength = memory[0]->u.Memory.Length;
    ctx->DspLength = memory[1]->u.Memory.Length;

    // Hard safety property of M0.5.1: device MMIO is mapped read-only and uncached.
    ctx->HdaBase = static_cast<PUCHAR>(MmMapIoSpaceEx(
        ctx->HdaPhysical,
        ctx->HdaLength,
        PAGE_READONLY | PAGE_NOCACHE));
    if (ctx->HdaBase == nullptr) {
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    ctx->DspBase = static_cast<PUCHAR>(MmMapIoSpaceEx(
        ctx->DspPhysical,
        ctx->DspLength,
        PAGE_READONLY | PAGE_NOCACHE));
    if (ctx->DspBase == nullptr) {
        MmUnmapIoSpace(ctx->HdaBase, ctx->HdaLength);
        ctx->HdaBase = nullptr;
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    ctx->ResourcesReady = TRUE;
    return STATUS_SUCCESS;
}

NTSTATUS
PhaserM051EvtReleaseHardware(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesTranslated
)
{
    UNREFERENCED_PARAMETER(ResourcesTranslated);

    auto ctx = PhaserM051GetContext(Device);
    ctx->ResourcesReady = FALSE;

    if (ctx->DspBase != nullptr) {
        MmUnmapIoSpace(ctx->DspBase, ctx->DspLength);
        ctx->DspBase = nullptr;
    }

    if (ctx->HdaBase != nullptr) {
        MmUnmapIoSpace(ctx->HdaBase, ctx->HdaLength);
        ctx->HdaBase = nullptr;
    }

    return STATUS_SUCCESS;
}

VOID
PhaserM051EvtIoDeviceControl(
    _In_ WDFQUEUE Queue,
    _In_ WDFREQUEST Request,
    _In_ size_t OutputBufferLength,
    _In_ size_t InputBufferLength,
    _In_ ULONG IoControlCode
)
{
    

    WDFDEVICE device = WdfIoQueueGetDevice(Queue);
    auto ctx = PhaserM051GetContext(device);

    NTSTATUS status = STATUS_INVALID_DEVICE_REQUEST;
    size_t information = 0;

    if (IoControlCode == IOCTL_PHASER_M051_SNAPSHOT && InputBufferLength == 0) {
        if (!ctx->ResourcesReady || ctx->HdaBase == nullptr || ctx->DspBase == nullptr) {
            status = STATUS_DEVICE_NOT_READY;
        } else if (OutputBufferLength < sizeof(PHASER_M051_SNAPSHOT)) {
            status = STATUS_BUFFER_TOO_SMALL;
        } else {
            PVOID buffer = nullptr;
            status = WdfRequestRetrieveOutputBuffer(
                Request,
                sizeof(PHASER_M051_SNAPSHOT),
                &buffer,
                nullptr);

            if (NT_SUCCESS(status)) {
                auto out = static_cast<PPHASER_M051_SNAPSHOT>(buffer);
                RtlZeroMemory(out, sizeof(*out));

                out->Magic = PHASER_M051_MAGIC;
                out->Version = PHASER_M051_VERSION;
                out->HdaPhysical = static_cast<ULONGLONG>(ctx->HdaPhysical.QuadPart);
                out->DspPhysical = static_cast<ULONGLONG>(ctx->DspPhysical.QuadPart);
                out->HdaLength = ctx->HdaLength;
                out->DspLength = ctx->DspLength;

                // M0.5.1 reads only five registers. No register write API exists.
                out->HdaGcap = static_cast<ULONG>(
                    READ_REGISTER_USHORT(
                        reinterpret_cast<volatile USHORT*>(ctx->HdaBase + HDA_REG_GCAP)));

                const UCHAR vmin = READ_REGISTER_UCHAR(
                    reinterpret_cast<volatile UCHAR*>(ctx->HdaBase + HDA_REG_VMIN));
                const UCHAR vmaj = READ_REGISTER_UCHAR(
                    reinterpret_cast<volatile UCHAR*>(ctx->HdaBase + HDA_REG_VMAJ));
                out->HdaVersion = (static_cast<ULONG>(vmaj) << 8) | vmin;

                out->DspAdspcs = READ_REGISTER_ULONG(
                    reinterpret_cast<volatile ULONG*>(ctx->DspBase + DSP_REG_ADSPCS));
                out->DspAdspis = READ_REGISTER_ULONG(
                    reinterpret_cast<volatile ULONG*>(ctx->DspBase + DSP_REG_ADSPIS));

                out->Flags = 0x00000001u; // resource gates passed; read-only snapshot valid
                information = sizeof(*out);
            }
        }
    }

    WdfRequestCompleteWithInformation(Request, status, information);
}
