#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate a C++ embedded firmware provider from the exact pinned SOF fixture.

This script performs no network access. The input must already exist and must
match tests/fixtures/sof_glk_reference.json exactly. Generated bytes are intended
for a build directory only and are not committed by this repository.
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys

PROVIDER = "GetEmbeddedFirmwareSource"


def fail(message: str) -> None:
    raise ValueError(message)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    pin_path = root / "tests" / "fixtures" / "sof_glk_reference.json"
    pin = json.loads(pin_path.read_text(encoding="utf-8"))

    data = args.input.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if len(data) != int(pin["size"]):
        fail(f"firmware size mismatch: {len(data)} != {pin['size']}")
    if digest.lower() != str(pin["sha256"]).lower():
        fail("firmware SHA-256 mismatch; refusing provider generation")

    lines = [
        "// GENERATED FILE - DO NOT EDIT OR COMMIT",
        "// Source identity is fixed by tests/fixtures/sof_glk_reference.json.",
        f"// Upstream commit: {pin['commit']}",
        f"// Upstream license: {pin['license_url']}",
        '#include "firmware_source.h"',
        "",
        "namespace phaser360 { namespace windows {",
        "",
        "alignas(16) static const UCHAR kEmbeddedFirmware[] = {",
    ]
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        rendered = ",".join(f"0x{value:02x}" for value in chunk)
        lines.append(f"    {rendered},")
    lines += [
        "};",
        "static_assert(sizeof(kEmbeddedFirmware)==kPinnedImageBytes,",
        '              "embedded firmware extent must match reviewed pin");',
        "",
        f"bool {PROVIDER}(FirmwareSourceView* out) noexcept {{",
        "    if(!out) return false;",
        "    out->data=kEmbeddedFirmware;",
        "    out->bytes=sizeof(kEmbeddedFirmware);",
        "    return true;",
        "}",
        "",
        "} }",
        "",
    ]
    rendered = "\n".join(lines)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")

    report = {
        "provider": PROVIDER,
        "input_bytes": len(data),
        "input_sha256": digest,
        "reference_commit": pin["commit"],
        "reference_url": pin["url"],
        "license_url": pin["license_url"],
        "generated_source_sha256": hashlib.sha256(
            rendered.encode("utf-8")
        ).hexdigest(),
        "network_access": "NONE",
        "runtime_file_io": "NONE",
    }
    report_text = json.dumps(report, indent=2, sort_keys=True) + "\n"
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(report_text, encoding="utf-8")
    print(report_text, end="")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"EMBEDDED_FIRMWARE_PROVIDER=FAIL: {exc}", file=sys.stderr)
        raise SystemExit(1)
